import express from "express";
import { z } from "zod";
import { prisma } from "../config/prisma.js";
import { authRequired } from "../utils/auth.js";
import { asyncRoute } from "../utils/http.js";
import { audit } from "../services/audit.js";
const router = express.Router();
router.use(authRequired);
router.get("/me", asyncRoute(async (req, res) => res.json(await prisma.business.findUnique({ where: { id: req.auth.businessId }, include: { subscription: true } }))));
router.patch("/me", asyncRoute(async (req, res) => {
  const data = z.object({ name: z.string().min(2).max(120).optional(), websiteUrl: z.url().nullable().optional(), googleBusinessUrl: z.url().nullable().optional(), currency: z.string().length(3).optional(), timezone: z.string().min(1).optional() }).parse(req.body);
  const business = await prisma.business.update({ where: { id: req.auth.businessId }, data });
  await audit({ businessId: req.auth.businessId, userId: req.auth.sub, action: "BUSINESS_UPDATED", entityType: "Business", entityId: business.id, metadata: data });
  res.json(business);
}));
router.get("/branches", asyncRoute(async req => req.res.json(await prisma.branch.findMany({ where: { businessId: req.auth.businessId }, orderBy: { createdAt: "asc" } }))));
router.post("/branches", asyncRoute(async (req, res) => { const data = z.object({ name: z.string().min(2), code: z.string().min(1).max(30), address: z.string().max(250).optional() }).parse(req.body); res.status(201).json(await prisma.branch.create({ data: { businessId: req.auth.businessId, ...data } })); }));
router.get("/staff", asyncRoute(async (req, res) => res.json(await prisma.user.findMany({ where: { businessId: req.auth.businessId, active: true }, select: { id: true, name: true, email: true, role: true }, orderBy: { name: "asc" } }))));
router.get("/sessions", asyncRoute(async (req, res) => res.json(await prisma.session.findMany({ where: { businessId: req.auth.businessId }, include: { endpoint: true, orders: { include: { items: true } }, payments: true }, orderBy: { createdAt: "desc" }, take: 100 }))));
router.get("/orders", asyncRoute(async (req, res) => res.json(await prisma.order.findMany({ where: { businessId: req.auth.businessId }, include: { items: true, session: true, branch: true, staff: true }, orderBy: { createdAt: "desc" }, take: 100 }))));
router.get("/payments", asyncRoute(async (req, res) => res.json(await prisma.payment.findMany({ where: { businessId: req.auth.businessId }, include: { session: true }, orderBy: { createdAt: "desc" }, take: 100 }))));
export default router;
